### ISSUE TITLE
Hacktober-fest Opportunity

### ISSUE THREAD

**Issue by tanwanimohit** [tanwanimohit/Hacktober-Fest-19#1]
Hello Guys, Hacktober is here..

**What can you do?**

- Fork this Repo.
- Make a Language Folder (Ex. Java, Don't make it, if already exists)
- Make file inside that folder and add your code. (add any code Like sorting algo or any compeitive program)
- Make a PR
- Star the Repo, That's it.

Share the Repo with your Friends.

**Comment by burhannn** [comment]
I will take this issue Can you assign
I want to make min 4 PullReqs

**Comment by tanwanimohit** [comment]
> I will take this issue Can you assign
> I want to make min 4 PullReqs

Go ahead i will approve your PR.
I cannot assign it as it is open for all.

**Comment by burhannn** [comment]
ok

**Comment by burhannn** [comment]
Hey can you please close my PRs ?

**Comment by burhannn** [comment]
thank you

**Comment by Loniks** [comment]
Hi, @tanwanimohit Could you please review and approve my p/r?

**Comment by Rangkynsai** [comment]
can i add a java program which is not a competitive program or sorting algorithm?.
